---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Sample VPC - Private and Public subnets'
Resources:
  MyNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: my-cluster
      NodegroupName: my-nodegroup
      # NodeRole: myAmazonEKSNodeR
      NodeRole: arn:aws:iam::790301748424:role/myAmazonEKSNodeRole
      Subnets:
        # - subnet-0803899084aa0b93f
        # - subnet-0415d65ffc1d7a68a
        - subnet-05113d6defb4bc9ec
        - subnet-0eba24d11694cf05e
        # - !GetAtt PublicSubnet01.SubnetId
        # - !GetAtt PublicSubnet02.SubnetId
        # - !GetAtt PrivateSubnet01.SubnetId
        # - !GetAtt PrivateSubnet02.SubnetId
      InstanceTypes:
        - t3.micro
      ScalingConfig:
        DesiredSize: 2
        MinSize: 1
        MaxSize: 3
